# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 15:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('clones', '0002_auto_20191013_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
