# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clones', '0006_auto_20191015_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_posted']},
        ),
    ]
